# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "standard_fkb_generell_del"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "felles_kartdatabase"
  system: "standardisering"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_standard_fkb_generell_del"
  title: "Security Champion standard_fkb_generell_del"
spec:
  type: "security_champion"
  parent: "land_security_champions"
  members:
  - "NilsIvarNes"
  children:
  - "resource:standard_fkb_generell_del"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "standard_fkb_generell_del"
  links:
  - url: "https://github.com/kartverket/standard_fkb_generell_del"
    title: "standard_fkb_generell_del på GitHub"
spec:
  type: "repo"
  owner: "security_champion_standard_fkb_generell_del"
  dependencyOf:
  - "component:standard_fkb_generell_del"
